name: pixero-automation-task
run-name: running tests
env:
  image_name: cucumber-playwright:$(date +%s)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: check image name
        run: echo "${{ env.image_name }} ${{ env.image_name }}"
      - name: Build docker images
        run: docker build . --file Dockerfile --tag ${{ env.image_name }}
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run container
        run: docker run --name ${{ env.image_name }}

